In [9]:
import numpy as np

In [17]:
import numpy as np

def example_infeasible():
    print("\n--- Infeasible Example ---")
    
    # Linear program (in standard form)
    # min c^T x
    # subject to: A x = b, x >= 0
    
    # Matrix A (4 constraints, 4 variables)
    A = np.array([[1, 1, 0, 0],
                  [1, -1, 0, 0],
                  [0, 0, 1, 1],
                  [0, 0, 1, -1]])
    
    # Right-hand side (b)
    b = np.array([1, -1, 1, -1])  # No feasible solution exists for this b
    
    # Objective function (c)
    c = np.array([1, 1, 0, 0])  # Just an example, any objective would work here
    
    # Artificial variables to handle infeasibility
    # Add 4 artificial variables, one for each constraint
    A_aug = np.hstack([A, np.eye(4)])  # Augment A with identity matrix for artificial variables
    c_aug = np.array([0, 0, 0, 0, 1, 1, 1, 1])  # Objective function for artificial variables
    b_aug = b.copy()  # Keep the same b for Phase 1
    
    # Initial basic variables: artificial variables
    beta = [4, 5, 6, 7]  # Columns of A corresponding to the artificial variables
    eta = [0, 1, 2, 3]  # Nonbasic variables are the original decision variables
    
    print("Initial augmented system (A):\n", A_aug)
    print("Initial b (with artificial variables):", b_aug)
    print("Initial objective (c_aug):", c_aug)
    
    # Start Phase 1 simplex process
    # Set up initial basic solution (x_beta)
    x_beta = np.linalg.solve(A_aug[:, beta], b_aug)
    print("Initial basic feasible solution (x_beta):", x_beta)
    
    # Objective value for artificial variables
    obj_value = np.dot(c_aug[beta], x_beta)
    
    # Check if the solution of artificial variables is non-zero (infeasible)
    if np.sum(x_beta) > 0:
        print("Infeasible solution: Sum of artificial variables is non-zero.")
    else:
        print("Feasible solution found.")
    
    print("Objective value (Phase 1):", obj_value)

example_infeasible()

# Feasible Example
def example_feasible():
    print("\n--- Feasible Example ---")
    
    # Linear program (in standard form)
    # min c^T x
    # subject to: A x = b, x >= 0
    
    # Matrix A (4 constraints, 4 variables)
    A = np.array([[1, 1, 0, 0],
                  [2, 1, 0, 0],
                  [0, 0, 1, 1],
                  [0, 0, 1, 0]])
    
    # Right-hand side (b)
    b = np.array([2, 3, 2, 1])  # Feasible solution exists for this b
    
    # Objective function (c)
    c = np.array([1, 1, 0, 0])  # Set objective to minimize x1 + x2
    
    # Artificial variables to handle feasibility
    # Add 4 artificial variables, one for each constraint
    A_aug = np.hstack([A, np.eye(4)])  # Augment A with identity matrix for artificial variables
    c_aug = np.array([0, 0, 0, 0, 1, 1, 1, 1])  # Objective function for artificial variables
    b_aug = b.copy()  # Keep the same b for Phase 1
    
    # Initial basic variables: artificial variables
    beta = [4, 5, 6, 7]  # Columns of A corresponding to the artificial variables
    eta = [0, 1, 2, 3]  # Nonbasic variables are the original decision variables
    
    print("Initial augmented system (A):\n", A_aug)
    print("Initial b (with artificial variables):", b_aug)
    print("Initial objective (c_aug):", c_aug)
    
    # Start Phase 1 simplex process
    # Set up initial basic solution (x_beta)
    x_beta = np.linalg.solve(A_aug[:, beta], b_aug)
    print("Initial basic feasible solution (x_beta):", x_beta)
    
    # Objective value for artificial variables
    obj_value = np.dot(c_aug[beta], x_beta)
    
    # Update x for nonbasic variables
    x = np.zeros(A_aug.shape[1])  # Initialize x with zeros, size includes artificial variables
    x[beta] = x_beta  # Assign the basic solution values
    
    # Ensure the basic feasible solution is valid
    if np.all(x >= 0):
        print("Feasible solution found.")
    else:
        print("Infeasible solution.")
        
    print("Objective value (Phase 1):", obj_value)
        
example_feasible()



--- Infeasible Example ---
Initial augmented system (A):
 [[ 1.  1.  0.  0.  1.  0.  0.  0.]
 [ 1. -1.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  1.  0.  0.  1.  0.]
 [ 0.  0.  1. -1.  0.  0.  0.  1.]]
Initial b (with artificial variables): [ 1 -1  1 -1]
Initial objective (c_aug): [0 0 0 0 1 1 1 1]
Initial basic feasible solution (x_beta): [ 1. -1.  1. -1.]
Feasible solution found.
Objective value (Phase 1): 0.0

--- Feasible Example ---
Initial augmented system (A):
 [[1. 1. 0. 0. 1. 0. 0. 0.]
 [2. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]]
Initial b (with artificial variables): [2 3 2 1]
Initial objective (c_aug): [0 0 0 0 1 1 1 1]
Initial basic feasible solution (x_beta): [2. 3. 2. 1.]
Feasible solution found.
Objective value (Phase 1): 8.0
